#!/bin/bash
azul="\033[0;34m"
red="\033[0;31m"
verde="\033[0;32m"
amarelo="\033[1;33m"
tag="\033[0m"
ativar() {
  [[ $(screen -list| grep -c 'bot_pix') == '0' ]] && {
    clear
    echo -e "${red}ATIVANDO BOT VENDAS..${tag}"
    sleep 4s
    screen -dmS "bot_pix"
    cd $HOME/BOT_VENDAS
    forever start index.js > /dev/null 2>&1
    echo ''
    echo -ne "${verde}BOT ATIVADO COM SUCESSO.${tag}"
    sleep 3s
    menu
} || {
    clear
    echo -e "${red}DESATIVANDO BOT VENDAS..${tag}"
    sleep 4s
    screen -r -S "bot_pix" -X quit
    cd $HOME/BOT_VENDAS
    forever stop index.js > /dev/null 2>&1
    echo ''
    echo -ne "${verde}BOT DESATIVADO COM SUCESSO.${tag}"
    sleep 3s
    menu
}
}

delete() {
    clear
    echo -e "${verde}REMOVENDO BOT VENDAS..${tag}"
    rm -r $HOME/BOT_VENDAS
    sleep 2s
    npm remove forever -g > /dev/null 2>&1
    sleep 2s
    npm remove nodemon -g > /dev/null 2>&1
    sleep 2s
    echo "y" | sudo apt-get remove nodejs > /dev/null 2>&1
    sleep 2s
    echo ''
    echo -e "${verde}BOT VENDAS REMOVIDO !${tag}"
    rm -r /bin/botssh
    sleep 2s
    exit 1
}

cancell() {
  echo -e "${red}CANCELADO COM SUCESSO !${tag}"
  sleep 2s
  main
}

remover() {
  clear
  echo ""
  echo -ne "${verde}RELMENTE DESEJA REMOVER O BOT SSH? (s/n)${tag}: "; read resp
  [[ "${resp}" = "N" || "${resp}" = "n" ]] && cancell
  [[ "${resp}" = "S" || "${resp}" = "s" ]] && delete
}


update() {
  clear
  echo ''
  echo -e "${verde} Essa função ainda em desenvolvimento..${tag}"
  sleep 3s
  menu
}

main() {
erro() {
 echo -e "${red} OPÇÃO INVALIDA ${tag}"
}
menu() {
 clear
 echo -e "${red}[${tag}01${red}]${tag} • ${amarelo}ATIVAR BOT VENDAS${tag}";
 echo -e "${red}[${tag}02${red}]${tag} • ${amarelo}ATUALIZAR BOT VENDAS${tag}"
 echo -e "${red}[${tag}03${red}]${tag} • ${amarelo}REMOVER BOT VENDAS${tag}"
 echo -e "${red}[${tag}00${red}]${tag} • ${amarelo}SAIR${tag}\n"
 echo -ne "${verde}INFORME UMA OPÇÃO: ${tag}";
 read resposta
}
menu
  [[ "${resposta}" = "1" || "${resposta}" = "01" ]] && ativar
  [[ "${resposta}" = "2" || "${resposta}" = "02" ]] && update
  [[ "${resposta}" = "3" || "${resposta}" = "03" ]] && { 
    remover return 0 
    }
  [[ "${resposta}" = "0" || "${resposta}" = "00" ]] && { 
    exit 1 
    }
  [[ "${resposta}" != "1" || "${resposta}" != "01" ||"${resposta}" != "2" || "${resposta}" != "02" || "${resposta}" != "3" || "${resposta}" != "03" ]] 
  erro 
  sleep 1s
  main
}
main